CREATE TABLE tCustomers (
  Id INT IDENTITY(1, 1) PRIMARY KEY,
  Name VARCHAR(50) NOT NULL,
  AddressLine1 VARCHAR(100) NOT NULL,
  AddressLine2 VARCHAR(200) NOT NULL,
  AddressLine3 VARCHAR NOT NULL
);
