-- GENERATED BY DEFAULT AS IDENTITY, see https://stackoverflow.com/questions/15810310/firebird-serial-field-as-in-pgsql/15810551#15810551
-- BLOB SUB_TYPE TEXT, see https://stackoverflow.com/questions/14682709/how-to-declare-a-field-as-varcharmax-in-firebird/14684972#14684972

CREATE TABLE "tCustomers" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Name" VARCHAR(50) NOT NULL,
  "AddressLine1" VARCHAR(100) NOT NULL,
  "AddressLine2" VARCHAR(200) NOT NULL,
  "AddressLine3" BLOB SUB_TYPE TEXT NOT NULL
);
