-- GENERATED BY DEFAULT AS IDENTITY, see https://stackoverflow.com/questions/15810310/firebird-serial-field-as-in-pgsql/15810551#15810551

CREATE TABLE "tOrders" (
  "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "OrderDate" TIMESTAMP NOT NULL,
  "CustomerId" INTEGER NOT NULL,
  FOREIGN KEY("CustomerId") REFERENCES "tCustomers"("Id")
);
